FROM ubuntu:latest

RUN apt update \
 && apt -y upgrade \
 && apt -y install \
		   cmake \
		   g++ \
                   pipx \
 && pipx install conan \
 && echo "PATH=/root/.local/bin:$PATH" >> /etc/bash.bashrc
